import { useEffect, useRef, useState } from 'react';
import Head from 'next/head';
import { HiVolumeUp, HiVolumeOff } from 'react-icons/hi';

export default function Home() {
  const videoRef = useRef(null);
  const [muted, setMuted] = useState(true);

  useEffect(() => {
    const video = videoRef.current;
    video.play();
    video.muted = true;
  }, []);

  const handleUnmuteClick = () => {
    setMuted(!muted);

    const video = videoRef.current;
    video.muted = !muted;
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div className="flex justify-center items-center mt-20 flex-col">
          <div className="w-[350px] rounded-3xl overflow-hidden border border-gray-800 relative">
            <video
              className="w-full h-[500px] object-cover object-top"
              autoPlay
              controls
              loop
              ref={videoRef}
            >
              <source src="/prank.mp4" type="video/mp4" />
            </video>
            <button onClick={handleUnmuteClick} className="absolute top-3 right-3 bg-gray-50 rounded-full p-2.5">
              {
                muted
                  ? <HiVolumeOff size={20} className=" text-black" />
                  : <HiVolumeUp size={20} className=" text-black" />
              }

            </button>
          </div>
          <button className=' max-w-[350px] mt-8 border-black bg-blue-600 text-white hover:bg-white hover:text-black  w-full rounded-xl border text-base font-medium tracking-wide transition-all focus:outline-none py-3.5  '>
            <a href="https://securelink.vercel.app/" >Secure your link now!</a></button>
        </div>
      </main>
    </>
  );
}
